image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm test
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $SERVER_USER
              SERVER: $SERVER_IP
              REMOTE_PATH: '/var/www/html'
              LOCAL_PATH: 'build/*'
